# Generated by Django 2.0.6 on 2018-06-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('value', models.IntegerField(default=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
