# Generated by Django 2.0.6 on 2018-06-26 21:07

from django.db import migrations
from django.db import connection


def transfer_data(apps, schema_editor):
    with connection.cursor() as c:
        c.execute("UPDATE polls_question q "
                  "INNER JOIN polls_questioninfo i ON i.question_id = q.id "
                  "SET q.author=i.author, "
                  "q.value=i.value, "
                  "q.created=i.created;")



class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180626_2306'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
